#ifndef _MACRO_H_
#define _MACRO_H_

#include "cocos2d.h"

#define WND_WIDTH 640
#define WND_HEIGHT 480
#define TEXT_COLOR (cocos2d::Color3B(191, 228, 230))
#define TEXT_FONT ("NanumBarunGothicBold")

enum RegionType
{
	RT_ALASKA_CANADA,
	RT_ARGENTINA_CHILE,
	RT_BRAZIL,
	RT_CARIBBEAN,
	RT_CENTRAL_AFRICA,
	RT_CENTRAL_AMERICA,
	RT_CHINA,
	RT_EAST_AFRICA,
	RT_EUROPE,
	RT_GREENLAND,
	RT_INDO,
	RT_JAPAN,
	RT_KOREA,
	RT_MEXICO,
	RT_NORTH_AFRICA,
	RT_NORTH_ASIA,
	RT_OCEANIA,
	RT_SOUTH_AFRICA,
	RT_SOUTH_EAST_ASIA,
	RT_SOUTH_WEST_ASIA,
	RT_WEST_AFRICA,
	RT_REGION_NUM,
};

#endif