#ifndef _MACRO_H_
#define _MACRO_H_

#include "cocos2d.h"

#define WND_WIDTH 640
#define WND_HEIGHT 480
#define TEXT_COLOR (cocos2d::Color3B(191, 228, 230))
#define TEXT_FONT ("NanumBarunGothicBold")
#define REGION_DEVELOP (cocos2d::Color3B(172,211,115))
#define REGION_UNKNOWN (cocos2d::Color3B(0,0,0))
#define REGION_DANGER (cocos2d::Color3B(255,64,64))
#define REGION_CAUTION (cocos2d::Color3B(255,149,25))
#define REGION_SAFE (cocos2d::Color3B(57,108,108))
#define REGION_MOVE (cocos2d::Color3B(204,204,204))
#define MAP_ORIGIN_X 93
#define MAP_ORIGIN_Y 387

enum RegionType
{
	RT_NONE = -1,
	RT_ALASKA_CANADA,
	RT_ARGENTINA_CHILE,
	RT_BRAZIL,
	RT_CARIBBEAN,
	RT_CENTRAL_AFRICA,
	RT_CENTRAL_AMERICA,
	RT_CHINA,
	RT_EAST_AFRICA,
	RT_EUROPE,
	RT_GREENLAND,
	RT_INDO,
	RT_JAPAN,
	RT_KOREA,
	RT_MEXICO,
	RT_NORTH_AFRICA,
	RT_NORTH_ASIA,
	RT_OCEANIA,
	RT_SOUTH_AFRICA,
	RT_SOUTH_EAST_ASIA,
	RT_SOUTH_WEST_ASIA,
	RT_WEST_AFRICA,
	RT_NUM,
};

#endif